Ellendar/Z2Randomizer

CLI/CLI.cs
CLI/CLI.csproj
RandomizerCore/Flags/FlagBuilder.cs
RandomizerCore/Flags/FlagReader.cs
RandomizerCore/Hyrule.cs
RandomizerCore/RandomizerConfiguration.cs
RandomizerCore/RandomizerCore.csproj
Z2Randomizer.sln

Right now, non-Windows users can't generate the ROM through the UI because it's Windows-only. However, the randomizer itself (Z2RandomizerCore project) is cross-platform, so with this commit, non-Windows users will be able to use a CLI to pass all the arguments necessary to generate the ROM (path to the original ROM, flags and a seed), along with misc options (remove flashing upon death and fast spell casting) and be able to generate the ROM.

feat: add CLI for cross-platform support (Issue #59)

---

.gitignore
Assembler/Assembler.csproj
CommandLine/Models/PlayerOptions.cs
CommandLine/PlayerOptionsService.cs
CommandLine/Program.cs
RandomizerCore/nlog.config

- Cleaned up spurious log files for non-Windows OSes
- Changed the console logging to use the logger so it's also logged to the log file
- Fixed some warnings around null safety checks
- Fixed a runtime exception based on incorrect version of Microsoft.ClearScript.V8 for Macos

Mac and Linux fixes for the command line

---

RandomizerCore/Hyrule.cs
RandomizerCore/Sidescroll/PalaceRooms.cs
RandomizerCore/Util.cs

FileExists and ReadAllTextFromFile operations on the PalaceRooms.json or CustomRooms.json will first try the current working directory and fall back to the directory the executable is in.

Update file operations on room configuration files to safekt fall back

---

CrossPlatformUI.Desktop/DesktopFileService.cs

This PR fills in some of the DesktopFileService TODOs for MacOS and Linux.  I'm not sure what the PalacesBasePath is supposed to point for so I largely left it alone.

Add Macos and Linux path support

---

RandomizerCore/Music.cs
RandomizerCore/RandomizerCore.csproj

Error handling (and especially error reporting) in FtRandoLib was kind of left as a to-do, as it was not expected that non-developers would be creating music libraries. When Z2R decided to not have standard libraries but allow users to create their own, errors resulting in extremely unhelpful messages. 
This PR (in combination with changes to FtRandoLib) remedies that by providing more helpful errors and error messages that should be sufficient to quickly find the cause of most common library errors.

Make music loading error messages more helpful for non-programmers

---

RandomizerCore/Music.cs

Fix the bug where GP was not assigned music and ended up randomly having either vanilla GP, vanilla palace, or vanilla encounter music.
While fixing that, I realized Bagu's house was getting encounter music assigned to it.

Fix GP and Bagu having wrong music

---

.github/workflows/build.yaml

Get rid of it as it's not even supported and causes precommits to always fail.

Remove MacOS 12 From GitHub Build

---

RandomizerCore/Hyrule.cs

I tested both with and without ShuffleSpells() being called.
Previously it must have relied on ShuffleSpells() being called, and perhaps additional conditions.

Consistently make Fire Spell "Pair With Random" link both ways

---

RandomizerCore/Enemies.cs
RandomizerCore/Sidescroll/SideviewEnums.cs

This replaces the IDs in the comments in Enemies.cs. Z2 Edit has multiple names for the flying enemies (skull, unicorn, rat, wolf). I'm going with Bubble, Dragon Head and Wolf Head consistently here. There were some other names that were inconsistent that I took a stance on.
I ended up using a mix of enums and consts. C# has some nice features for using switch cases on enums. However, C# enums cannot be extended or share values with other enums such that they compare as equal. They do compare equal to their int value, so the classes with int constants are used for the Shared variants. The goal is to minimize the likelihood of future errors.
The Sideview map command enums also gets a similar update.

Create enums for palace enemies

---

RandomizerCore/Enemies.cs
RandomizerCore/PalaceRooms.json
RandomizerCore/Sidescroll/EnemiesEditable.cs
RandomizerCore/Sidescroll/Room.cs
RandomizerCore/Sidescroll/SideviewEditable.cs
RandomizerCore/Sidescroll/SideviewEnums.cs
RandomizerCore/Sidescroll/SideviewMapCommand.cs
ValidateRooms/Program.cs

[Clean up and improve ValidateRooms](https://github.com/Ellendar/Z2Randomizer/commit/ce24ce18b7665c16d29d387a9de6ee5fec4fda7a) 
- Allow suppressing warnings based on a warning ID, instead of suppressing
warnings for the entire room - which was very error-prone.
- Now validate linked rooms.
- Utilize an exact solid block grid for better calculations.
- Check for multiple items in a single page.
- Add validation for elevator param.
[Update PalaceRooms with some minor changes](https://github.com/Ellendar/Z2Randomizer/commit/b4279525d9a9ac2b3a0fc64f32d2b51a5290fb1f) 
- Remove suppressValidation, add suppressWarning
- Drop waffles room: Remove illegal map command at the end. It had a window map command at y = 15 which is not valid.
- aaron jam 4_4 P5_M49: Change to not be a drop room (had lava …

Better validation & minor room fixes that I found

---

RandomizerCore/ROM.cs

If you went into a palace before DM, DM would use the elevator param from your last palace room. Now it loads its own param (they are all 0).

Fix AllowForChangingElevatorYPosition for Death Mountain elevators

---

RandomizerCore/Enemies.cs
RandomizerCore/Hyrule.cs
RandomizerCore/Sidescroll/EnemiesEditable.cs
RandomizerCore/Sidescroll/Room.cs
RandomizerCore/Sidescroll/SideviewEditable.cs

[Refactor RandomizeEnemies to use EnemiesEditable and the new enemy enums](https://github.com/Ellendar/Z2Randomizer/commit/9674e6d9c3778ba18431089bc9f23cf8cd20878d) 
- Renamed Palace125Enemies, Palace346Enemies, and GPEnemies to *GroundEnemies to prevent confusion (they do not include ALL enemies)
- Palace*Enemies arrays now uses enums
- StandardPalace*Enemies arrays still uses ints since they span two different enums
- GP*Enemies arrays uses enums only
[Modify RandomizeEnemies to utilize a solid grid for better randomization](https://github.com/Ellendar/Z2Randomizer/commit/49a493a29b75a950f07f31bb57c7c0ddd5fe61b9) 
- No longer roll Stalfos where they will get stuck (basically low ceilings)
- Make sure King Bots only roll where they have room (in 3x2 open tiles - so not in Waffle rooms)

Enemy refactor and small improvements

---

RandomizerCore/Hyrule.cs
RandomizerCore/ROM.cs

First, refactoring, then the following changes:
[Never randomize experience for 1ups lower than regular levels](https://github.com/Ellendar/Z2Randomizer/commit/6099e98c76dd22f4624c01c8ac55d7bbd575726f)
This solves the annoyance of level capping a stat, and having the 1-up level ups for that stat get in the way of maximizing crystal exp for the other stats. I think it's also a change that is wanted for regular stat-uncapped seeds.
This, however, introduces another problem that also had to be solved. The problem being that it gets easier to get a lot of crystal exp from capping one stat at a low level and maxing it out early, effectively making the game easier. Capping a stat level should still make the game harder.
(I know this is solved by the Scaling exp option, but that option also …

Refactoring and changing the way level up works when level cap is less than 8

---

RandomizerCore/Enemies.cs
RandomizerCore/Hyrule.cs
RandomizerCore/Overworld/DeathMountain.cs
RandomizerCore/Overworld/EastHyrule.cs
RandomizerCore/Overworld/MazeIsland.cs
RandomizerCore/Overworld/WestHyrule.cs
RandomizerCore/Sidescroll/EnemiesEditable.cs

I did some more work here to try to have less logic functions writing directly to the ROM bytes. Also a lot of the magic number addresses could be cleaned up now!
[Extract cleaner RandomizeEnemyAttributes method from RandomizeStartingValues](https://github.com/Ellendar/Z2Randomizer/commit/35db97972e9b3b3813ef0636f7bc5e9bc1dee355) 
This also adds a few missing enemies from the XP randomization:
- Blue dragon heads in Palace 125
- Mew, Acheman, Fokkeru (Spicy Chickens), King bots in GP
[Enemies that roll sword immune are set to be damageable by Fire](https://github.com/Ellendar/Z2Randomizer/commit/861fd098e7eaf3e870358fd2298ee58cd6586a42)

Enemy attributes improvements

---

CommandLine/DefaultPlayerOptions.json
CommandLine/Models/PlayerOptions.cs
CommandLine/PlayerOptionsService.cs
CommandLine/Sample.json
CrossPlatformUI/ViewModels/Tabs/SpritePreviewViewModel.cs
CrossPlatformUI/Views/Tabs/SpritePreviewView.axaml
RandomizerCore/Hyrule.cs
RandomizerCore/ROM.cs
RandomizerCore/RandomizerConfiguration.cs
RandomizerCore/RandomizerProperties.cs
RandomizerCore/SpritePatcher.cs

Basically I made a specific IpsPatcher patch method for the custom sprites. It checks every address that is being modified by a patch, and it skips changes if they are not in the whitelisted ROM address ranges. The code is very similar to the other patch method, but it didn't seem reasonable to bloat that function with a bunch of new if-checks. Better to keep it simple.
The goal is to make it impossible for custom sprites to introduce crashes or hard-to-track-down bugs. I did try it with a couple of seeds and I can't tell any difference, which is a good thing.
Everything in the CHR range has been allowed. What I did was put a breakpoint for everything it hit and ended up with a ton of ranges modified by the different IPS sprites that come included. I did my best to identify and take a …

Custom sprite IPS sanitization

---

RandomizerCore/Hyrule.cs
RandomizerCore/Overworld/EastHyrule.cs
RandomizerCore/RandomizerConfiguration.cs
RandomizerCore/RandomizerProperties.cs
RandomizerCore/Sidescroll/ChaosPalaceGenerator.cs
RandomizerCore/Sidescroll/CoordinatePalaceGenerator.cs
RandomizerCore/Sidescroll/Palaces.cs
RandomizerCore/Sidescroll/RandomWalkCoordinatePalaceGenerator.cs
RandomizerCore/Sidescroll/ReconstructedPalaceGenerator.cs
RandomizerCore/Sidescroll/Room.cs
RandomizerCore/Sidescroll/SequentialPlacementCoordinatePalaceGenerator.cs
RandomizerCore/Sidescroll/SideviewEditable.cs
RandomizerCore/Sidescroll/SideviewEnums.cs
RandomizerCore/Sidescroll/VanillaPalaceGenerator.cs

For now there are clouds at the entrance + Iron Knuckles inside the walls by the elevator to indicate the number of item rooms. (Exactly how we want this to look can easily be tweaked as desired.)
The logic has been changed to handle one count per palace (1-6).
There is also a possibility for higher rolls for the larger palaces.

Random palace item room count *per palace* with visual indicators

---

CommandLine/Sample.json
CrossPlatformUI/BuiltinPreset.cs
CrossPlatformUI/Views/Tabs/ItemsView.axaml
RandomizerCore/Hyrule.cs
RandomizerCore/RandomizerConfiguration.cs
RandomizerCore/RandomizerProperties.cs

Someone suggested this at some point, as a solution for often having to 100% seeds, looking for the glove. Now that there's potentially plenty of free item locations, this feature is low hanging fruit... if we want it. Of course, it probably makes the game easier and seeds shorter.
After the normal item shuffle is done, this feature will go through the items, and make one copy of each important item, replacing minor items (like P-bags), as space allows. There will only be as many duplicates as there are minor items to replace.
What is duplicated, in order (and if they are in the pool) is: Glove, Down stab, Fairy, Thunder, Reflect, Magic key, Hammer, Raft, Flute, Jump, Upstab, Boots.
It seems to be working well. The only bug I found is with stat tracking. Stat tracking lists multiple …

Add option to Allow Duplicates Of Important Items

---

CommandLine/Sample.json
CrossPlatformUI/BuiltinPreset.cs
CrossPlatformUI/Views/Tabs/PalacesView.axaml
RandomizerCore/EnumTypes.cs
RandomizerCore/RandomizerConfiguration.cs
RandomizerCore/RandomizerProperties.cs
RandomizerCore/Sidescroll/CoordinatePalaceGenerator.cs
RandomizerCore/Sidescroll/Palace.cs
RandomizerCore/Sidescroll/ReconstructedPalaceGenerator.cs
RandomizerCore/Sidescroll/VanillaShufflePalaceGenerator.cs

This is proposed as a solution to the anticlimactic, very short GP's that sometimes happen.
How it works is it calculates the shortest path to Dark Link and invalidates the palace if it is shorter than the selected option. This adds some seed generation time, but not too much (plus it's optional.)

Add option to set Minimum Path To Dark Link (in number of rooms)

---

CrossPlatformUI.Desktop/Properties/PublishProfiles/FolderProfile.pubxml
CrossPlatformUI/CrossPlatformUI.csproj
Directory.Build.props
RandomizerCore/Music/Readme.txt
RandomizerCore/RandomizerCore.csproj

- Remove old RandomizerCore.csproj manifest stuff that may trigger something
- Update dependency versions
- Building for "Any CPU" instead of x64 seems to fix the Anti-Virus trigger
- Now only copying PalaceRooms.json (and not CustomRooms.json or package.json)
- Runtimes for other platforms should not be included now (this should probably half the install size).
(The program still runs fine for me. New DialogHost looks better.)

Update project to try to prevent Anti-Virus triggers

---

RandomizerCore/Asm/MMC5.s
RandomizerCore/Asm/z2ft.s
RandomizerCore/Asm/z2r.inc
RandomizerCore/Hyrule.cs
RandomizerCore/RandomizerConfiguration.cs
Tests/Tests.csproj

This might conflict with https://github.com/Ellendar/Z2Randomizer/pull/306 so if it does, merge that first and i'll rebase after.
Fixes custom music support in 4.4 by removing some of the code that was duplicated when redoing the MMC5 conversion.

Fix custom music

---

RandomizerCore/Asm/z2r.inc

Item presence bits for GP uses 32 bytes starting at $6C0, so there is a conflict with these addresses.
Maybe it's this easy to fix.

Move PpuCtrlForIrq & ScrollPosForIrq to avoid conflict with item bits
